api_key = "${AIRTABLE_API_KEY}"

[tables]
tweets = {   base_id = "appEo7LBNoYQRwEc0",   table_name = "Table1" }
pokemons = { base_id = "app2jJgrXCQirseg5", table_name = "Pokemon" }
act_as_prompts = {  base_id = "appRJZBZdoktzVWBM",  table_name = "ğŸ¿Act as Prompts" }
ai_art_prompts = {  base_id = "appRJZBZdoktzVWBM",  table_name = "ğŸ¨AI Art Prompts" }
content_creation_prompts = {  base_id = "appRJZBZdoktzVWBM",  table_name = "ğŸ™ï¸Content YouTube" }
prompt_engineer = {  base_id = "appRJZBZdoktzVWBM",  table_name = "ğŸ¤–Prompt Engineer" }


[settings]
rau_config_path = "/Users/n/.rau/config.toml"

[paths]
config_file = "/Users/n/.rau/config.toml"
cache_file = "/Users/n/.rau/available_fields_cache.json"
